### ISSUE TITLE
Setup patch `AddAlternativeProductIdentifierAttributes` add "text" attributes as "filterable"

### ISSUE THREAD

**Issue by lemanchs** [Itonomy/module-flowbox#11]
Hi,
after having upgraded to the 1.4.3 version of the module, we ran an issue on our product listing pages : 
the 3 attributes created with the setup patch https://github.com/Itonomy/module-flowbox/blob/1.4.3/src/Setup/Patch/Data/AddAlternativeProductIdentifierAttributes.php are declared with type "text" and with the attribute "filterable" to "true", and that creates the error below with our Elastic Search integration :

`ssh.eu-3.magento.cloud: [2021-09-07 07:02:52] report.CRITICAL: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_56_v168","node":"8EiuKSMCRnuTvSpQUznjDg","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory.\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"magento2_product_56_v168\",\"node\":\"8EiuKSMCRnuTvSpQUznjDg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory.\"}}],\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory.\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [ean] in order to load field data by uninverting the inverted index. Note that this can use significant memory.\"}}},\"status\":400} at /app/7t57if6dywbwe/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632)"} []`

**Comment by drazulay** [comment]
@lemanchs thanks for reporting, we will provide a fix for this.

**Comment by drazulay** [comment]
Solution seems to be here: https://github.com/magento/magento2/issues/29439#issuecomment-724246133

**Comment by drazulay** [comment]
Solution implemented, we are now testing it.

**Comment by drazulay** [comment]
Created PR #12 

Ready for review @andyschofieuk

**Comment by drazulay** [comment]
Pending release under a new package version.
