### ISSUE TITLE
"Composer require" isn't working.

### ISSUE THREAD

**Issue by jarcorreia** [Itonomy/module-flowbox#22]
```
  [InvalidArgumentException]
  Could not find a matching version of package itonomy/module-flowbox. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum
  -stability (stable).
```

**Comment by Beagon** [comment]
Hi @jarcorreia,

This module isn't available via Packagist. You must first "purchase" it for free at the Magento Marketplace before you can install it via composer.
Please purchase it here: https://marketplace.magento.com/itonomy-module-flowbox.html

**Comment by jarcorreia** [comment]
Thanks for the quick answer.
