### ISSUE TITLE
lazyLoad: issue --- Wrong usage of Elvis operator ?:

### ISSUE THREAD

**Issue by alpacaboy** [Itonomy/module-flowbox#6]
It seems like even though we set `lazyLoad: False ` in boolean (settings of your module) we'll be forced to use `lazyLoad: True`
Could you check it out?
I assume it should be 

'lazyload' => (bool) ($this->getData('lazyload') ?: false),

https://github.com/Itonomy/module-flowbox/blob/00b5a707c9e7e4971e7de41b43976c086a20a760/src/Block/Widget/Flow.php#L54

**Comment by RaphaelBronsveld** [comment]
Hi there! Thank you for the bug report. We have created an internal ticket for this and we'll take a look at this ASAP.

**Comment by RaphaelBronsveld** [comment]
Hi there,

Has been fixed in version 1.4.0 (currently awaiting marketplace review).
https://github.com/Itonomy/module-flowbox/commit/b82e28c5a7f5fd64317dd1925c6d0e04fb6d14a9
